DROP ALL OBJECTS;

CREATE TABLE "USERS"(
    "ID"        IDENTITY NOT NULL PRIMARY KEY UNIQUE,
    "NICKNAME"  VARCHAR(255) NOT NULL UNIQUE,
    "PASSWORD"  VARCHAR(255) NOT NULL,
    "EMAIL"     VARCHAR(255) NOT NULL UNIQUE,
    "TOKEN"     UUID UNIQUE
);

CREATE TABLE "IMAGES"(
    "ID"            IDENTITY NOT NULL PRIMARY KEY UNIQUE,
    "USERID"        INT NOT NULL,
    "IMAGE"         BLOB NOT NULL,
    "NAME"          VARCHAR(255) NOT NULL,
    "DESCRIPTION"   VARCHAR(255),
    "PUBLIC"        BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY ("USERID") REFERENCES "USERS"("ID")
);

CREATE TABLE "PLACES"(
    "ID"            IDENTITY NOT NULL PRIMARY KEY UNIQUE,
    "LATITUDE"      DECIMAL(8,6) NOT NULL,
    "LONGITUDE"     DECIMAL(9,6) NOT NULL,
    "NAME"          VARCHAR(255) NOT NULL,
    "DESCRIPTION"   VARCHAR(255),
    "IMAGEID"       INT,
    "USERID"        INT NOT NULL,
    FOREIGN KEY ("USERID") REFERENCES "USERS"("ID"),
    FOREIGN KEY ("IMAGEID") REFERENCES "IMAGES"("ID")
);

CREATE TABLE "TAGS"(
    "ID"            IDENTITY NOT NULL PRIMARY KEY UNIQUE,
    "TITLE"         VARCHAR(255) NOT NULL UNIQUE,
    "DESCRIPTION"   VARCHAR(255),
    "USERID"        INT NOT NULL,
    FOREIGN KEY ("USERID") REFERENCES "USERS"("ID")
);

CREATE TABLE "PLACESTAGS"(
    "ID"            IDENTITY NOT NULL PRIMARY KEY UNIQUE,
    "PLACEID"       INT NOT NULL,
    "TAGID"         INT NOT NULL,
    FOREIGN KEY ("PLACEID") REFERENCES "PLACES"("ID"),
    FOREIGN KEY ("TAGID") REFERENCES "TAGS"("ID")
);

CREATE TABLE "TOKENS"(
    "ID"            IDENTITY NOT NULL PRIMARY KEY UNIQUE,
    "TOKEN"         UUID NOT NULL UNIQUE,
    "ACCESSRIGHT"   CHAR NOT NULL,
    "CREATORID"     INT NOT NULL,
    "USERID"        INT,
    "TAGID"         INT NOT NULL,
    FOREIGN KEY ("USERID") REFERENCES "USERS"("ID"),
    FOREIGN KEY ("TAGID") REFERENCES "TAGS"("ID"),
    FOREIGN KEY ("CREATORID") REFERENCES "USERS"("ID"),
    CHECK ("ACCESSRIGHT" IN ('R', 'W'))
);